### ISSUE TITLE
AT-2.7: Event Preview

### ISSUE THREAD

**Issue by r-saba** [RGPosadas/LitterRally#100]
**Issue Tracking**

This acceptance test is for #128 (it was mistakenly classified as a TASK).
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-27-event-preview).

**User Acceptance Flow**

1. User logs in
1. User finds an event that interests them
1. User presses on the event card, bringing us to the preview page for the event

**Comment by ghiobi** [comment]
I approve of the acceptance criteria! 🚀
