### ISSUE TITLE
AT-7.6.1: Login as a User

### ISSUE THREAD

**Issue by r-saba** [RGPosadas/LitterRally#101]
**Issue Tracking**

This acceptance test is for #99.
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-76-login-as-a-user).

**User Acceptance Flow**

1. User opens the app
1. User sees multiple ways of logging in
    a. Through an existing service (Google, Twitter, Facebook, etc)
    b. Using user's email
1. User logs in
1. User sees the home page

**Comment by ghiobi** [comment]
I approve of the acceptance test.
