### ISSUE TITLE
BUG-10: Smaller screen widths not well supported

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#132]
**Describe The Bug**

Some smaller resolutions and screen widths aren't well supported by our application. This issue was first noticed in #125, where @JimLau49 mentioned the issue he saw with the refactor at smaller resolutions. @osahtout mentioned that this issue is already present in `develop` with something like the button navigation bar on mobile. Thus, this bug ticket was made.

**To Reproduce**

Steps to reproduce the behaviour:
1. Serve the front-end application
2. Adjust the screen width to be something less than 250px (easy to do with the "Device Toolbar" in Chrome, or "Responsive Design Mode" in Firefox)
3. See that parts of the design of the website are broken

**Expected Behavior**

We expect that the application layout and styling should be able to handle common device resolutions without breaking.

**Bug Handling Strategy**
- [ ] Fix it now
- [x] Fix it later

**Screenshots**

![image](https://user-images.githubusercontent.com/23544999/103425660-d87f0700-4b81-11eb-8087-731f001aeb3f.png)

**Comment by RGPosadas** [comment]
No longer relevant.
