### ISSUE TITLE
AT-7.1.2 & AT-7.6.2: OAauth Registration + Login

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#142]
**Issue Tracking**

This acceptance test is for both #30 and #99.
Since OAuth covers both registration and login, they are combined in this AT.
See the two tests running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-71-and-us-76-oauth-registration-and-login).

**User Acceptance Flow**

1. User opens the app
1. User sees Facebook, Twitter, and Google as ways to sign in
1. User logs in using one of these services
1. User is redirected to the app's home page

**Comment by ghiobi** [comment]
I approve of the acceptance test.
