### ISSUE TITLE
BUG-11: Fix material UI warnings when running tests on Location Autocomplete

### ISSUE THREAD

**Issue by JimLau49** [RGPosadas/LitterRally#160]
**Describe The Bug**

When running tests related to the location autocomplete component, the material UI error appears repeatedly specifying the usage of  the `getOptionSelected` prop in the material UI autocomplete component to be used for tests. 

**To Reproduce**

1. Go to develop branch.
2. `nx test mull-ui`
3. Observe the console for error messages/warnings

**Expected Behavior**

Material UI errors do not appear when running `nx test mull-ui`

**Bug Handling Strategy**
- [ ] Fix it now
- [x] Fix it later

**Screenshots**

![image](https://user-images.githubusercontent.com/35787279/105088124-796a2f00-5a69-11eb-905b-42565b8634c5.png)

**Comment by TheGreatMarkus** [comment]
Fixed in #197 incidentally, since they were annoying me. 

see this code: [link](https://github.com/RGPosadas/Mull/blob/develop/apps/mull-ui/src/app/pages/create-event/location-autocomplete/location-autocomplete-textbox.spec.tsx#L34)

**Comment by cristian-aldea** [comment]
Fixed in #197 incidentally, since they were annoying me. 

see this code: [link](https://github.com/RGPosadas/Mull/blob/develop/apps/mull-ui/src/app/pages/create-event/location-autocomplete/location-autocomplete-textbox.spec.tsx#L34)
