### ISSUE TITLE
BUG-13: API Called when clicking on "Current Location"

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#164]
**Describe The Bug**

When the user presses on the "Current Location" button in the location modal, it calls the API after a few moments, just like when the user types out an address.

**To Reproduce**

Steps to reproduce the behaviour:
1. Run both the frontend and backend
2. Put a console.log in the location autocomplete resolver, to see when its being claled
3. Go to the Create Event page and set your location to "Current Location"
4. See that the resolver is being called

**Expected Behavior**

We don't need to call the API when 

**Bug Handling Strategy**
- [ ] Fix it now
- [x] Fix it later

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5e160fac883b575ee8bdbf20/9e52f627-b621-41e7-9c4d-09545885a33a)
![image.png](https://images.zenhubusercontent.com/5e160fac883b575ee8bdbf20/41df1f92-061a-4d48-8cac-08d87e0f45ad)

**Comment by RGPosadas** [comment]
Fix in #179
