### ISSUE TITLE
BUG-14: JoinEvent Mutation Gets Called When Creating an Event

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#165]
**Describe The Bug**

When creating an event, the following GraphQL mutations are executed in this order:
1. JoinEvent
1. UploadFile 
1. CreateEvent

JoinEvent should not be called to begin with when creating an event.

**To Reproduce**

1. Go to https://www.mullapp.com or run the app locally
1. Inspect the page, then create an event (this will still be succesful)
1. You will see that there are 3 GraphQL calls (the ones mentioned above)

![image](https://user-images.githubusercontent.com/33991121/105499627-c4658b80-5c8f-11eb-94e3-dd1e71b32577.png)

**Expected Behavior**

Only UploadFile and CreateEvent should be called when creating an event.

**Bug Handling Strategy**
- [ ] Fix it now
- [x] Fix it later

**Desktop (please complete the following information):**

 - OS: macOS Catalina 10.15.7
 - Browser: Chrome
 - Version: 87.0.4280.88

**Comment by bit172** [comment]
This was fixed in #167. Closing for now.
