### ISSUE TITLE
BUG-15: Fix Need to Click Two Times Back Button

### ISSUE THREAD

**Issue by osahtout** [RGPosadas/LitterRally#175]
**Describe The Bug**

Sometimes, it is needed to click the back button twice to back. A fix is needed to ensure that the user only need to click once to go back to the previous page. 

**To Reproduce**

1. Go to any event
2. Click on the back button
3. Nothing should happen (if it does go back, click on an event in upcoming)
4. Click again and now it goes back

**Expected Behavior**

Only one click should be needed to go back

**Bug Handling Strategy**
- [ ] Fix it now
- [X] Fix it later

**Comment by cristian-aldea** [comment]
I unassigned myself from this ticket, I cannot reproduce the issue.

**Comment by cristian-aldea** [comment]
Currently no longer able to reproduce this issue. Tried on all my available devices (chrome, firefox, edge, android chrome) and everything worked as expected
