### ISSUE TITLE
US-3.2: Group Chat Page 

### ISSUE THREAD

**Issue by JimLau49** [RGPosadas/LitterRally#185]
**User Story Description**

As a participant, I want to have a group chat with the event members so that I can communicate with them.

**User Acceptance Flow**

1. User navigates to messaging page (announcements + group messaging) 
1. User views past messages from other participants 
1. User types a message and submits it
1. Message appears on the group messaging page 

**Acceptance Criteria**

- [ ] User is able to submit a message
- [ ] User is able to see existing messages
- [ ] Messaging is done in real-time
- [ ] Seeder is updated for new entities
- [ ] User Acceptance Flow is respected
- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] There must exist an automated Cypress acceptance test that tests the user acceptance flow
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=1749%3A28348)

**Hints**
- https://www.apollographql.com/docs/apollo-server/data/subscriptions/

**Comment by RGPosadas** [comment]
https://www.apollographql.com/docs/react/data/subscriptions/#subscribing-to-updates-for-a-query
