### ISSUE TITLE
AT-3.1: Announcements Page

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#192]
**Issue Tracking**

This acceptance test is for #156 .
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-31-announcements-page).

**User Acceptance Flow**

1. Host types an announcement
2. Host clicks submit
3. Announcement appears on the announcement page

**Comment by ghiobi** [comment]
I approved the acceptance criteria.
