### ISSUE TITLE
AT-3.2: Group Chat Page

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#193]
**Issue Tracking**

This acceptance test is for #185 .
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-32-group-chat-page).

**User Acceptance Flow**
1. User navigates to messaging page (announcements + group messaging) 
1. User views past messages from other participants 
1. User types a message and submits it
1. Message appears on the group messaging page

**Comment by ghiobi** [comment]
I approved the acceptance criteria.
