### ISSUE TITLE
AT-7.2: Müll Profile

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#221]
**Issue Tracking**

This acceptance test is for #31.
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-72-m%C3%BCll-profile).

**User Acceptance Flow**

**User Acceptance Flow**

1. User logs in to the app
1. User clicks on "Profile" button on the navigation bar
1. User sees their profile
1. User clicks on "Edit Profile" and edits their public profile information (name, description, avatar/icon)
1. User should now see their updated profile

**Comment by ghiobi** [comment]
I approve of the acceptance criteria! 🚀
