### ISSUE TITLE
AT-3.4: DMs Page

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#234]
**Issue Tracking**

This acceptance test is for #227 .
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-34-dms-page).

**User Acceptance Flow**

1. User logs in
1. User clicks on `Messages` page
1. User clicks on/searches for a person of interest to DM
1. User is now able to DM said person

**Comment by ghiobi** [comment]
I approve of this acceptance test.
