### ISSUE TITLE
AT-3.5: Photos in Posts

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#235]
**Issue Tracking**

This acceptance test is for #228 .
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-35-photos-in-posts).

**User Acceptance Flow**

1. User goes to any messaging page
1. User is able to upload a photo along their post

**Comment by ghiobi** [comment]
I approve of this acceptance test.
