### ISSUE TITLE
AT-1.6: Event Restriction

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#256]
**Issue Tracking**

This acceptance test is for #255.
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-16-event-restriction).

**User Acceptance Flow**

1. User clicks on `Create Event`
1. User is able to choose the event restriction (Public, Friends Only, Private)
1. User creates event
    1. Only public events can be discovered on Discover Events Page 
    1. Non-public events cannot be seen on Discover Events page

**Comment by ghiobi** [comment]
I approved the acceptance criteria.
