### ISSUE TITLE
AT-7.3: User Portfolio

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#268]
**Issue Tracking**

This acceptance test is for #267 .
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-73-user-portfolio).

**User Acceptance Flow**

1. User logs in
1. User goes to their profile page
1. User clicks on 'My Portfolio'
1. User sees a portfolio of their past events

**Comment by ghiobi** [comment]
I approve of this acceptance test.
