### ISSUE TITLE
AT-7.4: View Other User Profiles

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#271]
**Issue Tracking**

This acceptance test is for #270 .
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-74-view-other-user-profiles).

**User Acceptance Flow**
1. UserA logs in
1. UserA sees UserB's profile page

**Comment by ghiobi** [comment]
I approve of this acceptance test.
