### ISSUE TITLE
AT-8.1: Add Friends

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#274]
**Issue Tracking**

This acceptance test is for #273 .
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-81-add-friends).

**User Acceptance Flow**

1. User logs in
1. User goes to their Profile Page
1. User clicks on 'Add Friends'
1. Add Friends page shows up where they can search for friends, accept friend requests, and see pending friend requests

**Comment by ghiobi** [comment]
I approve of this acceptance test.
