### ISSUE TITLE
AT-8.5: Friends List

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#280]
**Issue Tracking**

This acceptance test is for #278 .
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-85-friends-list).

**User Acceptance Flow**

1. User logs in
1. User goes to their Profile Page
1. User clicks on 'My Friends'
1. User is able to see a list of their friends in alphabetical order

**Comment by ghiobi** [comment]
I approve of this acceptance test.
