### ISSUE TITLE
BUG-20 Messages Not Sorted by Date in Group Pages

### ISSUE THREAD

**Issue by osahtout** [RGPosadas/LitterRally#285]
**Description**
 
In the image below "Bbbb" was sent after "hi" but it's displayed before. 
It's possible that the messages are being sorted for each user separately.
 

**To Reproduce**

1. Sign in as a@a.com in mullapp.com or create event 1 in local dev
1. Sign in as another user and join event 1
1. Send messages as with the other user as the participant
1. Sign back in as the host and send messages

**Expected Behavior**

Messages should be sorted by date regardless of users

**Bug Handling Strategy**
- [ ] Fix it now
- [X] Fix it later

**Screenshots**

![image](https://user-images.githubusercontent.com/44760251/111037915-42beee00-83f4-11eb-9a75-0c2a41a7146a.png)

**Comment by RGPosadas** [comment]
I've noticed that this happens on and off
