### ISSUE TITLE
AT-5.2: Showing More Information About Identified Trash

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#288]
**Issue Tracking**

This acceptance test is for #34 .
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-52-showing-more-information-about-identified-trash).

Please note that we can currently only detect:
* bottle
* box
* computer keyboard
* food
* mobile phone
* plastic bag
* tin can

**User Acceptance Flow**

1. User presses on the Waste Recognition Tool button
1. Application requests access to the camera
1. User points the camera at an object they want to identify
1. Tool identifies the type of waste by showing icons that are hovering over the waste

**Comment by ghiobi** [comment]
I approve of this acceptance test.
