### ISSUE TITLE
TASK-28: Set Event Location

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#29]
**User Story Description**

As a host, I want to add the event location to my event so that participants can know where the event is hosted.

**User Acceptance Flow**

1. While creating an event, user has to fill in location field
1. Location field is autocompletes
1. User can choose between two options:
    1. Use current location
    1. Enter an address

**Acceptance Criteria**

- [ ] User acceptance flow is respected
- [ ] Documentation present where needed
- [ ] Unit and UI tests are implemented for every component and function
- [ ] There must exist an automated Cypress acceptance test in GIF form
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2000%3A222930)

**Comment by cristian-aldea** [comment]
For whoever ends up working on this, be careful on what type you end up using for the point:
![image](https://user-images.githubusercontent.com/23544999/98493160-c29b3880-2207-11eb-9cf9-d2c31c38f9ff.png)
point will need to be changed from a string to something else, to make it easier to use
