### ISSUE TITLE
BUG-22: Denial of Location Permission Saves Location as Current Location

### ISSUE THREAD

**Issue by cindyslittleplanet** [RGPosadas/LitterRally#306]
**Describe The Bug**

If you select Current Location, but then deny location permission, the location is saved as “Current Location”.

**To Reproduce**

1. Go to Create Events
2. Click on the Location textbox
3. Click on the "Current Location" option
4. Deny location permission
5. Click on Edit button to go back
6. Location is saved as "Current Location"

**Expected Behavior**
Throws an error that current location could not be found. 

**Bug Handling Strategy**
- [x] Fix it now
- [ ] Fix it later

**Comment by cristian-aldea** [comment]
I currently can't replicate the issue in this bug
![image.png](https://images.zenhubusercontent.com/5e160fac883b575ee8bdbf20/bb0e9317-ab4f-4e89-baca-ffb5af54b0cd)

When I follow the steps and then try to review it shows an error. However the fact that `Current Location` still shows up is a bug and will be fixed.

**Comment by cristian-aldea** [comment]
Nevermind found how the bug is caused. A previous valid location needed to have been selected. Then, the current location needs to be selected with permissions denied
