### ISSUE TITLE
AT-1.2: Upload Event Page Photo

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#38]
**Issue Tracking**

This acceptance test is for #28.
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-1-create-events).

**User Acceptance Flow**

1. While creating an event, user has to upload a photo as their event image
1. When user submits the event form, the uploaded image becomes the event preview image

**Comment by ghiobi** [comment]
Yes, I accept what has been done. Styling and look will be improved on at the end. Features are more important.
