### ISSUE TITLE
AT-1.3: Set Event Location

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#39]
**Issue Tracking**

This acceptance test is for #29.
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-11-create-events). Please keep in mind it's still the US-1.1 GIF, however it is updated to include location.

**User Acceptance Flow**

1. While creating an event, user has to fill in location field
1. Location field is autocompletes
1. User can choose between two options:
    1. Use current location
    1. Enter an address

**Comment by ghiobi** [comment]
I approve the acceptance test.
