### ISSUE TITLE
AT-5.1: Tool To Identify Types Of Waste

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#40]
**Issue Tracking**

This acceptance test is for #33.
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-51-Tool-To-Identify-Types-Of-Waste).

**User Acceptance Flow**

1. User presses on the Waste Recognition Tool button
1. Application requests access to the camera
1. User points the camera at an object they want to identify
1. Tool identifies the type of waste by showing icons that are hovering over the waste

Please note that the acceptance test GIFs are manual since it was difficult to make E2E tests for the ML tool.

**Comment by ghiobi** [comment]
I approved the acceptance criteria.
