### ISSUE TITLE
AT-7.1.1: Multiple Registration Options - Local Registration

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#41]
**Issue Tracking**

This acceptance test is for #30.
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-71-multiple-registration-options).

Note: The current E2E covers 1.b only as 1.a will be completed along with #99.

**User Acceptance Flow**

1. User opens the app
1. User sees multiple ways of registering
    a. Through an existing service (Google, Twitter, Facebook, etc)
    **b. Using user's email**
1. User chooses an option to make a Müll account

**Comment by ghiobi** [comment]
I approve of the acceptance test.
