### ISSUE TITLE
SPIKE-3: Setup React State Management

### ISSUE THREAD

**Issue by r-saba** [RGPosadas/LitterRally#46]
**Spike Description**

All frontend tickets will rely on react state management. Therefore, it is important to de-risk and have the knowledge to implement Apollo GraphQL or Redux. 

**Timebox**

2-3 Days

**After the Timebox**

Don't forget to document all spike findings as comments within the spike issue.

**Comment by r-saba** [comment]
I've finished researching Redux. I noticed NX can generate the template for us, therefore no code needs to be pushed and no follow-up ticket is required. I will hold a knowledge transfer to explain to the team how to generate the Redux stores and how to use them in our app.

**Comment by RGPosadas** [comment]
@r-saba Sounds good! Thanks for the research, you may close this ticket 🚀

**Comment by r-saba** [comment]
I am opening this back up. Since we have GraphQL in the backend we may be able to take advantage of Apollo Caching for state management over React Redux.

**Comment by r-saba** [comment]
Finished looking into this spike and held a knowledge transfer with the team. Below are some helpful resources.

[Repository demoing local state management in apollo](https://github.com/apollographql/ac3-state-management-examples/tree/master/apollo-local-state)
[React variables documentation](https://www.apollographql.com/docs/react/local-state/reactive-variables/)
