### ISSUE TITLE
AT-1.8: Review Event Creation

### ISSUE THREAD

**Issue by cindyslittleplanet** [RGPosadas/LitterRally#51]
**Issue Tracking**

This acceptance test is for #48.
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-18-review-event-creation).

**User Acceptance Flow**

1. User completed filling out the form
1. Press on "Submit" button
1. User is able to review the event information
   1. If user is unsatisfied with the form, user presses on "Edit" and returns to the form to make changes

**Comment by ghiobi** [comment]
Yes, I accept what has been done. 👍
