### ISSUE TITLE
AT-2.1: Show Events as a List on Discover Page

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#67]
**Issue Tracking**

This acceptance test is for #65 .
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-21-show-events-as-a-list-on-discover-page).

**User Acceptance Flow**

1. User lands on the home page, which is the discover page
1. User can choose to see:
   1. events relevant to them
   1. Upcoming events that they joined
   1. The events they created

**Comment by ghiobi** [comment]
I approve of the acceptance test but will need to work more on visuals later.
