### ISSUE TITLE
AT-2.8: Joining Events

### ISSUE THREAD

**Issue by RGPosadas** [RGPosadas/LitterRally#68]
**Issue Tracking**

This acceptance test is for #66 .
See the test running [here](https://github.com/RGPosadas/Mull/wiki/Acceptance-Test-GIFs#us-28-joining-events).

**User Acceptance Flow**

1. User logs in (Logged in user can be hard coded)
1. User finds an event that interests them on the Discover tab of the Home page
2.a User presses on the event card, bringing us to the preview page for the event. User presses "Join" on the event preview page
2.b User presses the join event button on the event card

**Comment by ghiobi** [comment]
I approve the acceptance test.
