### ISSUE TITLE
SPIKE-4: Determine Usability Testing Options

### ISSUE THREAD

**Issue by r-saba** [RGPosadas/LitterRally#86]
**Spike Description**

Research into Usability testing options. What software or libraries are available? What are the current best practices? Etc.

**Timebox**

3-4 days

**After the Timebox**

Don't forget to document all spike findings as comments within the spike issue.

**Comment by RGPosadas** [comment]
WIP documentation of this spike can be found [here](https://docs.google.com/document/d/1nQ0KyR9jkn-3Enbxss6VLclkXNB7rI-TEeVFijIJR80/edit?usp=sharing).

**Comment by RGPosadas** [comment]
Conclusion:
We are going with user session recordings using `hotjar`.
Gave the team a knowledge handover of what is usability testing, and how we are going to use hotjar in the future.

Usability Testing Timeline:
* Sprint #4: Complete usability testing SPIKE
* Sprint #5: Have a deployable application for users to access
* Sprint #6: Gather users (first half of the sprint), then analyze the user session recordings (second half of the sprint)

The spike is now finished, therefore I will close the ticket.
