### ISSUE TITLE
BUG-1: Failed Travis builds due to pre-commit even though pre-commit passes locally

### ISSUE THREAD

**Issue by r-saba** [RGPosadas/LitterRally#88]
**Describe The Bug**

In #77 a bug was introduced which caused pre-commit to pass locally but to fail on Travis. Travis fails while running pre-commit on `package-lock.json` which is autogenerated. The two git hooks which are failing are, Fix End of Files and prettier.

**To Reproduce**

1. Run the build on Travis

**Expected Behavior**

pre-commit should pass on Travis if it passes locally.

**Additional Context**

The bug has temporarily been silenced by excluding `package-lock.json` from pre-commit.

**Bug Strategy**
- [ ] Fix it now
- [ ] Fix it later
- [x] Won't fix

**Comment by cristian-aldea** [comment]
This bug will be left on the backburner until Travis CI is back online

**Comment by bit172** [comment]
Travis is no more. Closing for now.
