### ISSUE TITLE
BUG-2: Unable to connect to database due to invalid use of Null value

### ISSUE THREAD

**Issue by ys-lin** [RGPosadas/LitterRally#91]
**Describe The Bug**
When running `nx serve mull-api`, I wasn't able to connect to the database due to an invalid use of Null value error.

**To Reproduce**

1. Add entries to the user table in the database
2. Run `nx serve mull-api`
3. See error

**Expected Behavior**

I was expected to be able to connect to the database after running `nx serve mull-api`. 

**Screenshots**

<img width="931" alt="Screen Shot 2020-11-26 at 7 26 52 PM" src="https://user-images.githubusercontent.com/36641869/100398591-58fb9680-301d-11eb-9e4f-d1607cfeded6.png">

**Additional Context**
When I looked into the database, I discovered that there are entries with null passwords in the user table. I deleted all entries from the user table and I could connect to the database again when running `nx serve mull-api`.

**Comment by RGPosadas** [comment]
Closing since this is a continuity error for devs using the same database. 

Current workaround proposal: any devs using unmerged tables should be using their local database.
