### ISSUE TITLE
BUG-4: Lint errors don't fail travis builds

### ISSUE THREAD

**Issue by cristian-aldea** [RGPosadas/LitterRally#95]
**Describe The Bug**

Linting errors currently don't fail travis builds. Linting errors are currently on develop and should have been automatically caught by our ci.

Example: https://travis-ci.com/github/RGPosadas/Mull/builds/204533831

**To Reproduce**

1. Run a travis build on current develop
2. See logs

**Expected Behavior**

When a linting error (not warning) is caught, it should fail the build.

**Bug Strategy**
- [ ] Fix it now
- [ ] Fix it later
- [x] Won't fix

**Comment by RGPosadas** [comment]
This bug will be left on the backburner until Travis CI is back online

**Comment by bit172** [comment]
Travis is no more. Closing for now.
