### ISSUE TITLE
TASK-25: Event Members Component

### ISSUE THREAD

**Issue by r-saba** [RGPosadas/LitterRally#97]
**Task Description**

As a developer, I want a Component which given some user images will show them as per our mockup. This component will be used in event cards as well as on the event page.

**Acceptance Criteria**

- [ ] Documentation present where necessary
- [ ] Unit and UI tests are implemented for every component and function
- [ ] Must match [Mockup](https://www.figma.com/file/FJPXMYI4ULCnuCEZvPs67k/Mull?node-id=2000%3A343291)

**Comment by RGPosadas** [comment]
Pass in an array of photos as a prop, no backend code for now
